### ISSUE TITLE
Copy change and URL update request - webassembly

### ISSUE THREAD

**Issue by ejregithub** [mozilla/moz-games#131]
@potch - the Dev Marketing team (Porfirio) would like to ask for a copy and URL change in the games.mozilla.org site.  

The requested changes are documented [here](https://docs.google.com/spreadsheets/d/1CpqccqEG36MrGVQGjv8XZwQ16hBNYxGftDq76T-eAn8/edit#gid=660825393) in line 8

Please mpluta@mozilla.org with any questions.

Thanks,

Eric

**Comment by cvan** [comment]
I emailed mpluta@mozilla.org, and got a bounced-back email. Is that the correct email still?

**Comment by ejregithub** [comment]
@cvan - please ping mpluta@mozilla.com if you have any questions (or find him on Slack)

**Comment by moz-mpluta** [comment]
Hey cvan, 

just confirming that TL&I have made some updates to the changes we would like on the Games page, [here](https://docs.google.com/a/mozilla.com/spreadsheets/d/1CpqccqEG36MrGVQGjv8XZwQ16hBNYxGftDq76T-eAn8/edit?usp=sharing)

To summarize, we are looking to make 3 changes:
1. Change copy and CTA for WebAssembly 
2. Replace Open Web Games tile with WebVR tile (New copy, Image and CTA link)
3. Reorder all of the cards. 

Please let me know if you have any questions.

**Comment by cvan** [comment]
@moz-mpluta

I've made these changes in Pull Request #133.

1. Because [the site](https://games.mozilla.org/)'s background colour of the card footers is white, and the image for the new WebVR card has a white background, the lack of contrast looked a bit awkward alongside the "Firefox Hardware Report" card. Compare the two images below, and let me know your thoughts.
2. I also replaced the WebAssembly image with one with the updated branding. Let me know if you think that looks fine.
3. Everything else look okay to you? If so, I'll merge PR #133 and push it live to https://games.mozilla.org/

<hr>

![screenshot-2017-8-15 mozilla the future of web games 1](https://user-images.githubusercontent.com/203725/29338293-69762c06-81c9-11e7-833f-82cf3d522c9e.png)

<hr>

![screenshot-2017-8-15 mozilla the future of web games](https://user-images.githubusercontent.com/203725/29338327-8087cee0-81c9-11e7-8899-e6c4f13e0812.png)

**Comment by moz-mpluta** [comment]
Hey @cvan 

Thank you, this is great! I had a look with Porfirio and we think that the second version with the grey band looks better. 

After looking at the punctuation, we would like to change the copy of the VR subhead 
From: Build in A-Frame. Share in Firefox.
To: Build VR with A-Frame and share files in Firefox

This way the copy will have consistent punctuation on the page.

**Comment by cvan** [comment]
> This way the copy will have consistent punctuation on the page.

Yeah, np, I thought it looked a bit inconsistent. Just changed to `Build VR with A-Frame and share files in Firefox`

**Comment by cvan** [comment]
What about changing `and share files in Firefox` to `and enjoy VR in Firefox`?

**Comment by moz-mpluta** [comment]
hey @cvan, that sounds good, let's do it. Thanks!

**Comment by cvan** [comment]
done, and pushed to production: https://games.mozilla.org/

<hr>

a few additional notes:

I filed issue #134 for updating the Mozilla branding.

I don't work on the Games projects anymore, although I did work on the initial version of this site. it was then redesigned by a firm Andre worked with.

I know @potch has been helping out with maintenance on this. but just mentioning this because there are a couple outstanding issues (#119 and #138), namely around page-load perf (namely the artwork: [1] the background graphic and [2] the graphic headline).

**Comment by moz-mpluta** [comment]
Thank you @cvan this is looking fantastic! We really appreciate your help.

**Comment by moz-mpluta** [comment]
Hey @cvan, when reviewing the live page, Judy noticed that the headline copy for VR and WebAssembly is identical... We really apologize about the back and forth on this, but would it be possible to change the copy one last time?

This change to VR tile would solve the issue:

Hed: WebVR Ships in Firefox
Deck: Build new virtual worlds in A-Frame

**Comment by cvan** [comment]
@moz-mpluta: updated: https://games.mozilla.org/

the text for the WebVR card is now a tad longer than those of the other cards. let me know if you want me to tweak this further or if there are any other changes you'd like made.

**Comment by cvan** [comment]
@moz-mpluta: I adjusted the font size of the headings now. see Pull Request #143: https://github.com/mozilla/moz-games/pull/143#issue-255495687

you can see the change now at https://games.mozilla.org/
